resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: codeway/templates
      endpoint: ghe
      ref: team_phoenix_databricks_pipelines
    - repository: jobs
      type: githubenterprise
      name: supplies-bd/team-phoenix-databricks-jobs-config
      endpoint: ghe

variables:
- group: databricks-itg
- group: Defaults
- name: jobs_file
  value: jobs.yml
- name: stack
  value: itg

trigger: 
  branches:
    include:
    - master
  paths:
    exclude:
      - databricks/internal/dev-springboard.yml
      - itg-databricks/internal/itg-springboard.yml
      - prod-databricks/internal/prod-springboard.yml
      - databricks/internal/dev-jobs.yml
      - itg-databricks/internal/itg-jobs.yml
      - prod-databricks/internal/prod-jobs.yml
      - README.md

pr: none

pool: 'CodeWayAWSLinux'

jobs:
  - template: projects/dataos/stages/databricks_deployment-v1.yml@templates
    parameters:
      account: '435705730031'
      region: 'us-west-2'
      roleARN: $(dataos_core_itg_internal_databricks_cd_role_arn)
      externalId: $(dataos_core_itg_internal_databricks_cd_external_id)
      secrets:
        - secretName: arn:aws:secretsmanager:us-west-2:828361281741:secret:codeway/databricks/deployment/phoenix-itg-internal-Mocxdh
          secretProperty: token
          variable: DATABRICKS_TOKEN
        - secretName: arn:aws:secretsmanager:us-west-2:828361281741:secret:codeway/deployment/nexus-2V3n6v
          secretProperty: password
          variable: NEXUS_PASSWORD
        - secretName: arn:aws:secretsmanager:us-west-2:828361281741:secret:codeway/deployment/nexus-2V3n6v
          secretProperty: username
          variable: NEXUS_USERNAME
      configs:
        "DATABRICKS_HOST": "https://dataos-itg-internal.cloud.databricks.com"
      conf_prefix: 'team-phoenix-databricks-jobs-config/jobs'
      scripts_prefix: 'templates'
      library_path_prefix: 'dbfs:/dataos-pipeline-springboard'
      workspace_path_prefix: '/team-phoenix'
      nexus_repo: "https://nexus-int.corp.hpicloud.net/repository"
      jobs_file: $(jobs_file)
      stack: $(stack)
      jobs_file_prefix: 'team-phoenix-databricks/itg-databricks'
