CREATE OR REPLACE VIEW financials.v_adjusted_revenue_yoy_ci_details
AS SELECT adjusted_revenue_growth_ci_details.record_description, adjusted_revenue_growth_ci_details.cal_date, adjusted_revenue_growth_ci_details.fiscal_year_qtr, adjusted_revenue_growth_ci_details.fiscal_yr, adjusted_revenue_growth_ci_details.geography, adjusted_revenue_growth_ci_details.geography_grain, adjusted_revenue_growth_ci_details.region_3, adjusted_revenue_growth_ci_details.region_5, adjusted_revenue_growth_ci_details.pl, adjusted_revenue_growth_ci_details.l5_description, adjusted_revenue_growth_ci_details.technology, adjusted_revenue_growth_ci_details.accounting_rate, sum(adjusted_revenue_growth_ci_details.inventory_change_impact) AS tier_1_usd_current_qtr, sum(adjusted_revenue_growth_ci_details.prior_year_inventory_impact) AS tier_1_usd_prior_qtr, sum(adjusted_revenue_growth_ci_details.currency_impact_ch_inventory) AS valuaton_t1_current_qtr, sum(adjusted_revenue_growth_ci_details.currency_impact_ch_inventory_prior_period) AS valuation_t1_prior_qtr, sum(adjusted_revenue_growth_ci_details.current_quarter_impact_total_tier1) AS current_qtr_total_tier_1, sum(adjusted_revenue_growth_ci_details.prior_quarter_impact_total_tier1) AS prior_qtr_total_tier_1, adjusted_revenue_growth_ci_details.flash, adjusted_revenue_growth_ci_details.version
   FROM ( SELECT f.record_description, f.cal_date, f.fiscal_year_qtr, f.fiscal_yr, f.geography, f.geography_grain, f.region_3, f.region_5, f.pl, f.l5_description, plx.l6_description, f.technology, f.accounting_rate, COALESCE(sum(f.inventory_change), 0::double precision) AS inventory_change_impact, COALESCE(sum(f.ci_change_prior_year), 0::double precision) * -1::double precision AS prior_year_inventory_impact, COALESCE(sum(f.ci_currency_impact), 0::double precision) AS currency_impact_ch_inventory, COALESCE(sum(f.ci_currency_change_prior_year), 0::double precision) * -1::double precision AS currency_impact_ch_inventory_prior_period, COALESCE(sum(f.total_inventory_change), 0::double precision) AS current_quarter_impact_total_tier1, COALESCE(sum(f.total_ci_change_prior_year), 0::double precision) * -1::double precision AS prior_quarter_impact_total_tier1, 
                CASE
                    WHEN f.version::text = '2021.05.18.1'::text THEN 'May Flash'::text
                    WHEN f.version::text = '2021.08.12.1'::text THEN 'Q321 Actuals @ July Rates'::text
                    WHEN f.version::text = '2021.08.12.2'::text THEN 'Aug Flash @ Aug Rates'::text
                    WHEN f.version::text = '2021.11.10.1'::text THEN 'Q421 Actuals @ Oct Rates'::text
                    WHEN f.version::text = '2022.02.17.1'::text THEN 'Q122 Actuals @ Jan Rates'::text
                    WHEN f.version::text = '2022.05.03.1'::text THEN 'April Flash @ May Rates'::text
                    WHEN f.version::text = '2022.05.12.1'::text THEN 'Q222 Actuals @ April Rates'::text
                    WHEN f.version::text = '2022.08.15.1'::text THEN 'Q322 Actuals @ July Rates'::text
                    WHEN f.version::text = '2022.11.09.1'::text THEN 'Q422 Actuals @ Oct Rates'::text
                    ELSE concat(to_char(f.load_date, 'Month'::text), ' Flash'::text)
                END AS flash, f.version, f.load_date
           FROM fin_prod.adjusted_revenue_flash f
      LEFT JOIN mdm.product_line_xref plx ON f.pl::text = plx.pl::text
     WHERE 1 = 1 AND (f.version::text = '2022.02.17.1'::text OR f.version::text = '2022.05.12.1'::text OR f.version::text = '2022.08.15.1'::text OR f.version::text = '2022.10.13.1'::text OR f.version::text = '2022.11.09.1'::text OR f.version::text = '2022.11.11.1'::text)
     GROUP BY f.record_description, f.cal_date, f.fiscal_year_qtr, f.fiscal_yr, f.geography, f.geography_grain, f.pl, f.l5_description, plx.l6_description, f.technology, f.accounting_rate, f.version, f.region_3, f.region_5, f.load_date) adjusted_revenue_growth_ci_details
  GROUP BY adjusted_revenue_growth_ci_details.record_description, adjusted_revenue_growth_ci_details.cal_date, adjusted_revenue_growth_ci_details.fiscal_year_qtr, adjusted_revenue_growth_ci_details.fiscal_yr, adjusted_revenue_growth_ci_details.geography, adjusted_revenue_growth_ci_details.geography_grain, adjusted_revenue_growth_ci_details.pl, adjusted_revenue_growth_ci_details.l5_description, adjusted_revenue_growth_ci_details.technology, adjusted_revenue_growth_ci_details.accounting_rate, adjusted_revenue_growth_ci_details.region_3, adjusted_revenue_growth_ci_details.region_5, adjusted_revenue_growth_ci_details.version, adjusted_revenue_growth_ci_details.flash;

-- Permissions

  grant delete, insert, references, select, trigger, update on financials.v_adjusted_revenue_yoy_ci_details to group phoenix_dev;